### ISSUE TITLE
Textures on some games are broken.

### ISSUE THREAD

**Issue by christmerlini** [OpenEmu/Mupen64Plus-Core#1]
The 3D objects are usually fine and work really well.
However, textures in some games appear to be missing or broken.
I don't know if this is a "me" problem, but I have a feeling it's a general problem.
Since the games are still playable, I have no problem with it personally.
But if it could be fixed, it'd definitely be a huge plus.

Silicon Valley
![screen shot 2013-06-23 at 1 00 09 am](https://f.cloud.github.com/assets/2473448/691509/889d87d0-db8f-11e2-9fc5-d5dc7b445286.png)

Pokemon Stadium Gold Silver
![screen shot 2013-06-23 at 12 54 06 am](https://f.cloud.github.com/assets/2473448/691502/b8a75092-db8e-11e2-9a9c-9ed017c4d5a3.png)

Mario Tennis 64
![screen shot 2013-06-23 at 1 03 06 am](https://f.cloud.github.com/assets/2473448/691510/0f41181a-db90-11e2-8f7d-4bfdd3aaace1.png)

**Comment by mrvacbob** [comment]
This is #5 then.
