### ISSUE TITLE
Paper Mario Problems

### ISSUE THREAD

**Issue by Amazee-Dayzee** [OpenEmu/Mupen64Plus-Core#10]
When I try to play Paper Mario, I run into a few problems while playing it. Among them, when I am in a dark room I only get silhouettes of characters and when I am in full screen, the emulator is very slow. Also, when I save to one save file, all of the save files on the title screen are saved to different files. And I think sometimes the sprites get distorted briefly. Anyway I can fix these issues?

**Comment by clobber** [comment]
Sorry, no. These are bugs in the GPU plugin (Rice) used by our Mupen64Plus implementation. We're not responsible for these sorts of issues. Some day they may be resolved with a speedy software rasterizer. Also please keep in mind we show this warning for N64 for a reason:
![4d66a968-5c93-11e4-97e1-b2dd5b3dd23a](https://cloud.githubusercontent.com/assets/1303132/8178297/3b7d1862-13d2-11e5-8da7-3f1e90d7775c.png)
