### ISSUE TITLE
Audio channels reversed

### ISSUE THREAD

**Issue by OMGsus** [OpenEmu/Mupen64Plus-Core#11]
I've noticed this in many forks if not all... i think its with sdl getting from the output "left-first" but sdl assumes "right-first"...

instead of swapping by env config, might be better to fix by changing

if(SwapChannels == 0)

to

if(SwapChannels == 1)

I dunno.. up to you guys... Possibly fixed but I can't build or test from here. Im testing on 2.0.1 (as release on experimental)

**Comment by clobber** [comment]
We don't use SDL or audio plugins. Swapping would need to be handled in our implementation.

**Comment by OMGsus** [comment]
Doh... then i am unaware. sorry i can't help more. all i can do is complain then :P 

Thanks!

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mupen64Plus-Core/commit/c6775d13682103de4be7a39fdd5a102bb3b240e2
