### ISSUE TITLE
Mupen64 doesn't seem to be available on the compiled version.

### ISSUE THREAD

**Issue by JFK108** [OpenEmu/Mupen64Plus-Core#12]
Anyone wanna help me out? I compiled OpenEmu so I could finally play multi-disc ps1 games which just didn't work in experimental. Now that I have compiled it and am finally playing disc 2 of Metal Gear, I realize that the N64 core isn't available. Any suggestions or changes? Will all these features be together in the next release?

**Comment by clobber** [comment]
Did you try looking under Library in Preferences?

**Comment by JFK108** [comment]
It has a check mark as well as an exclamation mark

**Comment by clobber** [comment]
Then you didn't actually compile the 'Experimental' scheme and all its cores. Seriously though, this isn't the place for this - take it back to reddit. We are working on next release and everything will be included when it is ready.

**Comment by JFK108** [comment]
I didn't mean to come off as aggressive, I asked on reddit and they said to come here. Sorry for the misdirection.
