### ISSUE TITLE
Only shows part of the display

### ISSUE THREAD

**Issue by emilygracevee** [OpenEmu/Mupen64Plus-Core#13]
Only 1/4 of the screen is showing; the rest is black. I've tried all the filters but no dice. Just a quarter of the screen showing; the game works fine.

**Comment by clobber** [comment]
I'm guessing Harvest Moon 64? Sorry, that is a bug with the Rice GPU plugin and nothing we can do about it.

**Comment by emilygracevee** [comment]
Thanks Clobber, how did you know??
