### ISSUE TITLE
World Rally 2 Open Emu 

### ISSUE THREAD

**Issue by GatecrasherUK** [OpenEmu/Mupen64Plus-Core#24]
Hello .. pretty new to the Github thing, but can someone please help me to get a copy of World Rally 2 (Gaelco) to work please via OpenEmu. I am showing a :Coprocessor not ready fault ....from my downloaded rom. Thanks in advance =)

**Comment by clobber** [comment]
You seem to be describing an Arcade game and not N64. Mupen64Plus is for N64. Arcade game support is experimental and unsupported in OpenEmu right now.
