### ISSUE TITLE
Choppy audio and laggy gameplay with 2.5.4, fixed by reverting to 2.5.3

### ISSUE THREAD

**Issue by tupelo-schneck** [OpenEmu/Mupen64Plus-Core#25]
I'm running OpenEmu v2.0.6.1 on a Mac mini (Mid 2011) running High Sierra 10.13.2.

With the Mupen64Plus core 2.5.4, audio is noticeably choppy and gameplay feels laggy (I tried Super Mario 64 and Paper Mario).  If I revert to 2.5.3 everything seems fine again.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues/3447
