### ISSUE TITLE
Use of undeclared identifier 'g_rdram' in MupenGameCore.m

### ISSUE THREAD

**Issue by StenApp** [OpenEmu/Mupen64Plus-Core#26]
Getting this error on Mupen64plus core: Use of undeclared identifier 'g_rdram' in MupenGameCore.m when compiling original OpenEmu with Build_All option.

Can this caused by?:
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.

Using MacOS 10.13.6

**Comment by clobber** [comment]
Compiles just fine on stable Xcode. You are likely trying to update a plugin on your own by plunking in files, which is unsupported by us. Once again, stop pestering about GLideN64.
