### ISSUE TITLE
Star Wars : Rogue Squadron only showed half screen when Mupen64Plus-Core updated to 2.5.5

### ISSUE THREAD

**Issue by Gankosakae** [OpenEmu/Mupen64Plus-Core#27]
It was worked normally in previous Mupen64Plus-Core versions.
When Mupen64Plus-Core updated to version 2.5.5 and the game showed just like the following picture.
![2018-09-22 8 24 57](https://user-images.githubusercontent.com/29351630/45917256-c5126b00-bea5-11e8-8412-4de2ee469aaf.png)

**Comment by clobber** [comment]
Mupen64Plus and GPU plugin bug. Regressions are possible. This may improve in a future version of Mupen64Plus and GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mupen64Plus-Core/commit/239ed5f1c470ea48e782a9ebf9709a7fa8c577ee

This is fixed now.

Restart the app and an updated Mupen64Plus core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Mupen64Plus 2.5.7
