### ISSUE TITLE
Image is garbage

### ISSUE THREAD

**Issue by TechGuyOnTGB** [OpenEmu/Mupen64Plus-Core#30]
When I launch mupen64plus via retroarch, the image is garbage and the audio is broken. Please don't give me tips for configuration. Shame on you because the thing isn't working out-of-the-box in every computer.
![capture](https://user-images.githubusercontent.com/35379582/50339493-72863080-0520-11e9-9e91-77ce5218a6c0.PNG)

**Comment by clobber** [comment]
Wrong repo, you stupid idiot. This is OpenEmu.
