### ISSUE TITLE
Diddy Kong Racing freezes at 2nd Wizpig race cut scene

### ISSUE THREAD

**Issue by jwillson** [OpenEmu/Mupen64Plus-Core#36]
This only happens within OpenEmu, not in Mupen64Plus standalone:

https://github.com/mupen64plus/mupen64plus-user-issues/issues/708
https://github.com/mupen64plus/mupen64plus-core/issues/945

**Comment by clobber** [comment]
The latest OpenEmu core plugin available is not yet synced with upstream.
