### ISSUE TITLE
Diddy Kong Racing freezes at 2nd Wizpig race cut scene

### ISSUE THREAD

**Issue by jwillson** [OpenEmu/Mupen64Plus-Core#37]
#36 was rejected because the core plugin was not synced with upstream. But even older versions (including 2.5) of upstream work in standalone (verified on macOS 12.3), and versions 2.5.7 and 2.5.9 do not work in OpenEmu. If the core plugins work outside of OpenEmu, then wouldn't the problem be with how they're being integrated into OpenEmu and not with the core plugins upstream? Perhaps I'm missing something?

**Comment by clobber** [comment]
> Perhaps I'm missing something?

Yes, indeed you are. I'm not sure if you're after some kind of "haha, gotcha devs" or whatever. The core plugins do not work outside of OpenEmu. Mupen64Plus standalone is not a "core plugin". OpenEmu is not a launcher for executables. There is the difference of settings, RDP and RSP plugins which all affect game compatibility. I'm really not going to discuss this further as that is pointless.
