### ISSUE TITLE
Mario Kart 64 Sound Issue and Incomplete Renders.

### ISSUE THREAD

**Issue by alexjones14** [OpenEmu/Mupen64Plus-Core#38]
Hi team. I've been so spoiled with the fantastic work done on OpenEmu. As a complete emulation newbie I find it all so fascinating. I have had a very smooth ride with playing LOZ Ocarina of Time via Mupen64Plus, but when I play Mario Kart 64 I experience overall issues with gameplay music and complete sound loss after 20-30 minutes of gameplay on my MacBook Pro (13-inch, 2019) using OpenEmu v2.3.3 and Mupen64Plus v2.5.9.

I have sinced came to understand that I can toggle gameplay music using "L", but this seems to exasperate the issue of complete loss of sound. I toggle from "music loud" to "music soft" to "music off" and then my sound cuts out completely, without being able to recover from it. I did notice that my laptop was running hot, but I have played LOZ Ocarina of Time for hours before with no hitches.

I have a single Intel Iris Plus Graphics 645 (1536 MB) Graphics processor, a 1,4 GHz Quad-Core Intel Core i5 main processor, and 8 GB of RAM.

There also seems to be an issue rendering the train in the Kalimari Desert track in any gameplay setting except for Time Trails. But for now, my main issue remains the loss of sound.

**Comment by ilciavo** [comment]
Which version of OSX are you running? 

There seems to be a problem with [Monterrey](https://www.reddit.com/r/OpenEmu/comments/11rkvqz/n64_audio_issues_on_ios_monterey/). I've upgraded to 12.6.4 (Processor: 2 GHz Dual-Core Intel Core i5), but I have the same issue with audio. 

Checking a the implementation I've found that this could be related to SDL audio buffering.  

The following line was commented out in the frontend:

`l_CallerUsingSDL = (SDL_WasInit(0) != 0);
`

After adding it back, I've found that it's not supported on arm64. 

In addition, under general settings the binary 'linkage.o' was added and 'dyna_start.o' was removed.

**Comment by alexjones14** [comment]
@ilciavo Thanks for responding, especially on such an old thread! Thanks for the thorough breakdown. I don’t understand the technicality of the issue, but I feel better knowing that I wasn’t the only one. I was about to update my software to

**Comment by ilciavo** [comment]
> @ilciavo Thanks for responding, especially on such an old thread! Thanks for the thorough breakdown. I don’t understand the technicality of the issue, but I feel better knowing that I wasn’t the only one. I was about to update my software to Ventura anyway, so hopefully it works this time round. Will send an update.

Let me know how it goes
