### ISSUE TITLE
Glide64 MK2 Video Plugin does not work

### ISSUE THREAD

**Issue by dbellingroth** [OpenEmu/Mupen64Plus-Core#5]
If enabled in the source code the glide64 mk2 videoplugin only produces a black screen. For some games, glide64 mk2 works much better.

**Comment by alex-chandel** [comment]
Enabling Glide64 or Glide64 MK2 would fix longstanding graphical bugs in our Rice plugin, like Pokemon Snap photos not showing up (rendering the game unplayable), or the scrambled Mario Party 3 mini-game textures.

**Comment by alex-chandel** [comment]
OpenEmu currently ships with `mupen64plus-video-glide64.so`, `mupen64plus-video-glide64mk2.so`, and `mupen64plus-video-GLideN64.so`.

Are all of these non-functional?

**Comment by clobber** [comment]
>Are all of these non-functional?

...yes. If any/all of them worked, certainly GLideN64 would be the default in use.

**Comment by clobber** [comment]
We've implemented GLideN64 by gonetz (not to be confused with Glide64 or Glide64mk2) as the new default GPU plugin. This will ship out in an update soon.

**Comment by ricardo85x** [comment]
Hi thanks for you hard work
any change to update the GLideN64 to the latest version?
Now it support Star Wars Rogue Squadron!
Thanks!

**Comment by KevinKurtz** [comment]
Confirmed that Glide fixes issues in Diddy Kong Racing adventure two where rice will not render reversed maps. (Playable in M64Py on Mac, but not openemu). Would love to see Glide integrated as it seems to render many games better than Rice.
