### ISSUE TITLE
Software rendering plugin for N64

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/Mupen64Plus-Core#8]
Better to have accuracy than speed.

http://forum.pj64-emu.com/showthread.php?t=4422
https://github.com/libretro/mupen64plus-libretro/tree/master/mupen64plus-video-angrylion

**Comment by mrvacbob** [comment]
Also might have better compat (same author as angrylion):

https://github.com/purplemarshmallow/z64/tree/master/src

https://github.com/purplemarshmallow/GLideN64/tree/master/src

**Comment by clobber** [comment]
Also VIGL which is a multi-platform cleanup, GL blitting, fork of angrylion's software RDP but needs to be converted to Mupen64Plus 2.0 API: http://www.emutalk.net/threads/55481-angrylion-s-Per-Pixel-RDP-with-OpenGL

**Comment by clobber** [comment]
Added in https://github.com/OpenEmu/Mupen64Plus-Core/commit/a53de5ce4d78b437a1cb93c0bed041a2d7f68724
